[package]
name = "kestrel-glommio"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kestrel-core   = { path = "../kestrel-core" }
kafka-protocol = { workspace = true }
bytes          = { workspace = true }
thiserror      = { workspace = true }
futures-lite   = "2"
glommio        = { git = "https://github.com/dahankzter/glommio", rev = "2acb59d1" }
