[package]
name = "kestrel-tokio"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kestrel-core   = { path = "../kestrel-core" }
kestrel-client = { path = "../kestrel-client" }
tokio          = { version = "1", features = ["net", "io-util", "time", "rt"] }

[dev-dependencies]
kafka-protocol = { workspace = true }
bytes          = { workspace = true }
tokio          = { version = "1", features = ["macros", "rt-multi-thread"] }
